name: AbstractForm
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4533540103584528
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7c5d0'
    - '#bc6051'
    - '#868885'
    - '#232321'
    - '#484846'
  brandStrength: 0.0625
  lightness: 0.8481767422053963
  saturation: 0.6060210955329239
  rhythmicContrast: 0.7390751934144646
purpose: []
